---
title: "Analysis_Markdown"
---

This project answers two questions: does the Citibike program have a gender skew, and what are the differences in usage of the program between male and female riders. Using the month of June 2013 (cleaned in Pandas to remove data points with unknown gender), the report uncovers evidence of enormous gender skew in ridership, as 78.8% of riders whose gender was known were male. As for differences in ridership, the differences in trip duration were modest; however, despite male riders’ trips being shorter on average than trips taken by female riders, male riders showed greater variation in trip length. This finding suggests that male riders have more varied reasons for their use of the Citibike program than do female riders.
	The map shows a cluster of stations, mostly on the perimeter just South of central park. The two outlier stations furthest South have sparse ridership figures (250 and 112 started trips, respectively, compared to a station average of 1,003 for the entire NYC Citibike program). Since they are the two closest stations to more NYC residents than any others, this suggests that demand for the Citibike program as it is currently structured is not uniform across the city. This could also mean that when one of the key benefits of the Citibike program– that riders can finish in a different location than they started– is absent, demand for the program plummets. However, the cluster of stations East of the East River and North of the harbor also have sparse ridership levels, averaging 351 started trips during the month compared to the Citibike average, despite having a similar advantage to the two outlier stations. This suggests that the Citibike program has a concentration of demand in Manhattan.